#!/usr/bin/env bash
cat > /dev/null <<EOC
netstat -nlp | grep tcp
tcp        0      0 209.236.74.138:993          0.0.0.0:*                   LISTEN      25870/dovecot       
tcp        0      0 209.236.74.138:995          0.0.0.0:*                   LISTEN      25870/dovecot       
tcp        0      0 127.0.0.1:64646             0.0.0.0:*                   LISTEN      32226/pplproxy      
tcp        0      0 127.0.0.1:3403              0.0.0.0:*                   LISTEN      28753/0             
tcp        0      0 127.0.0.1:3404              0.0.0.0:*                   LISTEN      28753/0             
tcp        0      0 209.236.74.138:110          0.0.0.0:*                   LISTEN      25870/dovecot       
tcp        0      0 0.0.0.0:9999                0.0.0.0:*                   LISTEN      30042/ssocks4       
tcp        0      0 209.236.74.138:143          0.0.0.0:*                   LISTEN      25870/dovecot       
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      1260/portmap        
tcp        0      0 209.236.74.138:465          0.0.0.0:*                   LISTEN      29089/stunnel       
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      13809/sshd          
tcp        0      0 127.0.0.1:631               0.0.0.0:*                   LISTEN      1579/cupsd          
tcp        0      0 0.0.0.0:1080                0.0.0.0:*                   LISTEN      19665/divert        
tcp        0      0 50.115.117.177:25           0.0.0.0:*                   LISTEN      30109/dummymail     
tcp        0      0 174.127.113.45:25           0.0.0.0:*                   LISTEN      1650/master         
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      1650/master         
tcp        0      0 0.0.0.0:633                 0.0.0.0:*                   LISTEN      1299/rpc.statd      
tcp        0      0 0.0.0.0:9339                0.0.0.0:*                   LISTEN      19665/divert        
tcp        0      0 ::1:3403                    :::*                        LISTEN      28753/0             
tcp        0      0 ::1:3404                    :::*                        LISTEN      28753/0             
tcp        0      0 :::22                       :::*                        LISTEN      13809/sshd  
EOC


function io.readln
{
	read -r
}

function io.writeln
{
	echo "$*"
}

explode_into() {
	local E e
	e="$( declare -p "${1}" )" && eval "declare -a E=${e#*=}"
	shift
	local i=0
	while (( $# )); do
		eval $1=\${E[\$i]}
		(( i++ ))
		shift
	done
}


function main
{
	IFS="$IFS/:" 
	while read -r tcp q1 q2 localip localport remoteip remoteport listen pid process
	do
		# tcp        0      0 209.236.74.138:993          0.0.0.0:*                   LISTEN      25870/dovecot       
		# 1			 2		  3 4       						  5									6			   7/8
		
		# cols=( $REPLY )
		if [[ $tcp == 'tcp' && $localip != '127.0.0.1' ]]; then
			# echo "${cols[@]}"
			# explode_into cols tcp q1 q2 localip localport remoteip remoteport listen pid process

			# -A INPUT -p tcp -m tcp -d 127.0.0.1
			# 123456789 123456789 123456  (26)
			# 26 + 15 + 5 + 19 + 2
			printf -v line -- '# Generated by Anonmous\n#%49s%s\n-A INPUT -p tcp -m tcp -d %-15s --dport %-5s -j ACCEPT\n\n' \
				"" "$process" "$localip" "$localport" 

			echo -n "${line/-d 0.0.0.0 /           }"
		fi
	done
}

cat <<EOF
*filter
:INPUT ACCEPT
:FORWARD ACCEPT
:OUTPUT ACCEPT
EOF

netstat -nlp | main 
echo COMMIT
